### ISSUE TITLE
cointrade traceback

### ISSUE THREAD

**Issue by kartikkannan** [toirl/cointrader#4]
* Cointrader version:
* Python version:2.7
* Operating System:opensuse leap 42.2

### Description
installed cointrader
added .cointrader config file in user home
executed cointrader --help

Tell us what happened, what went wrong, and what you expected to happen.
Traceback (most recent call last):
  File "/usr/bin/cointrader", line 7, in <module>
    from cointrader.cli import main
  File "/usr/lib/python2.7/site-packages/cointrader/cli.py", line 5, in <module>
    from .exchange import Poloniex
  File "/usr/lib/python2.7/site-packages/cointrader/exchange.py", line 3, in <module>
    from .exchanges.poloniex import Poloniex as PoloniexApi
ImportError: No module named exchanges.poloniex

### What I Did
tried installing directly from pip and by downloading from github and python setup.py install
Both give same error
```

**Comment by toirl** [comment]
Hi thank you for your report! I will look into it this weekend.
